name: Laravel

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  laravel-environment-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "7.4"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
  unit-tests:
    runs-on: ubuntu-latest
    needs: laravel-environment-setup
    steps:
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit ^latest
      - name: Execute PHPUnit tests
        run: vendor/bin/phpunit
  scan-vulnerabilities:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Scan image
        uses: anchore/scan-action@v2
        id: scan
        with:
          image: "zh4d0w/ucreativa-project:latest"
          grype-version: 0.13.0
          acs-report-enable: true
          fail-build: false
          severity-cutoff: critical
  build-docker-image:
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - uses: actions/checkout@master
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zh4d0w/ucreativa-project:latest
